---

- name: Make angr virtualenv
  become: no
  become_user: {{ ansible_user }}
  shell: "source /usr/share/virtualenvwrapper/virtualenvwrapper.sh && mkvirtualenv angr --python={{ python_path }} --no-site-packages"
  args:
    executable: /bin/bash
    creates: "{{ virtualenv_dir }}/angr"
  register: mkvirtualenv
  failed_when: 'mkvirtualenv.changed and "New python executable" not in mkvirtualenv.stdout'

- name: Install angr
  become: no
  become_user: {{ ansible_user }}
  pip:
    name: angr
    virtualenv: "{{ virtualenv_dir }}/angr"