---
- name: Configure a new ParrotOS from install
  hosts: laptop

  tasks:
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe
    
    - name: Update all packages
      apt:
        name: "*"
        state: latest
    
    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

  roles:
    - system_tools
    - user_interface
    - rust_tools
    - dev_tools
    - reversing_tools