---
- name: Configure a new ParrotOS from install
  hosts: laptop
  remote_user: root

  tasks:
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

  roles:
    - system_tools
    - user_interface
    - rust_tools
    - dev_tools
    - reversing_tools
