---
- name: Configure a new ParrotOS from install
  hosts: laptop
  become: true
  become_user: root
  vars_files:
    - './vars/system_tools_vars.yml'
    - './vars/dev_tools_vars.yml'
    - './vars/reversing_tools_vars.yml'

  roles:
    - init
    - system_tools
    - user_interface
    - dev_tools
    - rust_tools
    - reversing_tools

- name: Set up zsh for our user
  hosts: laptop
  become: no
  vars:
    local_user: "{{ ansible_user }}"
  tasks:
    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ local_user }}"
        shell: /bin/zsh