---

- name: Download and install bat (cat, but better, and written in Rust)
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb
    dpkg_options: force-confdef,force-confold,ignore-depends=libgcc1
  when: ansible_userspace_architecture == 'x86_64' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == "Parrot GNU/Linux")
  tags: bat