---
- name: Install some basic system necessities first
  apt:
    pkg:
    - zsh
    - zsh-common
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - neovim
    - rxvt-unicode
    - sysstat
    - htop
    - atop
    - git
    - rdesktop
    - openvpn
    - python-dev
    - gimp
    - inkscape
    - sqlite3
    - sqlite3-doc
    - imagemagick
    - grass
    - spatialite-gui
    - spatialite-bin
    - qgis
    - pandoc
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - xclip
    - xsel
    - yank
    - fonts-noto
    - fonts-mplus
    - filezilla
    - gummi
    - texmaker
    - wireshark
    - cifs-utils
    - meld
    - thefuck
    - python3-selinux
    - firejail
    - firejail-profiles

- name: Download and install Veles
  apt:
    deb: https://github.com/codilime/veles/releases/download/2018.05.0.TIF/Veles_2018.05_64bit_Ubuntu1604.deb
  when: ansible_userspace_architecture == 'x86_64' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == "Parrot GNU/Linux")

- name: Download and install Min (web browser)
  apt:
    deb: https://github.com/minbrowser/min/releases/download/v1.16.0/min_1.16.0_amd64.deb
  when: ansible_userspace_architecture == 'x86_64' and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == "Parrot GNU/Linux")

- name: Check for zshrc
  become: no
  local_action: stat path=/home/{{ ansible_user }}/.zshrc
  register: zshrc_present

- name: Set up oh-my-zsh
  become: no
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: zshrc_present.stat.exists is defined and zshrc_present.stat.exists