---
- name: Install i3 wm
  apt:
    pkg:
    - i3-wm
    - i3lock
    - i3lock-fancy
    - i3status

- name: Install some extra tools to make window manager better
  apt:
    pkg:
    - suckless-tools
    - dunst
    - compton
    - hsetroot
    - rofi
    - xsettingsd
    - lxappearance
    - scrot
    - viewnior