---
- name: Install i3 wm
  apt:
    pkg:
    - i3-wm
    - i3lock
    - i3lock-fancy
    - i3status

- name: Install some extra tools to make window manager better
  apt:
    pkg:
    - suckless-tools
    - dunst
    - compton
    - hsetroot
    - rofi
    - xsettingsd
    - lxappearance
    - scrot
    - viewnior
    - feh
    - font-manager

- name: Ensures /home/{{ ansible_user }}/.config dir exists
  become: no
  file: path=/home/{{ ansible_user }}/.config state=directory

- name: Copy compton config
  become: no
  template:
    dest: /home/{{ ansible_user }}/.config/compton.conf
    src: compton.conf.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: compton

- name: Ensures /home/{{ ansible_user }}/.config/i3 dir exists
  become: no
  file: path=/home/{{ ansible_user }}/.config/i3 state=directory
  tags: i3

- name: Copy i3 config
  become: no
  template:
    dest: /home/{{ ansible_user }}/.config/i3/config
    src: i3_config.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [i3config, i3]

- name: Ensures /home/{{ ansible_user }}/.config/i3status dir exists
  become: no
  file: path=/home/{{ ansible_user }}/.config/i3status state=directory
  tags: [i3status, i3]

- name: Copy i3status config
  become: no
  template:
    dest: /home/{{ ansible_user }}/.config/i3status/config
    src: i3status_config.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [i3status, i3]

- name: Ensures /home/{{ ansible_user }}/.config/dunst dir exists
  become: no
  file: path=/home/{{ ansible_user }}/.config/dunst state=directory
  tags: dunst

- name: Copy dunstrc
  become: no
  template:
    dest: /home/{{ ansible_user }}/.config/dunst/dunstrc
    src: dunstrc.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [dunstrc, dunst]

- name: Copy .xsettingsd
  become: no
  template:
    dest: /home/{{ ansible_user }}/.xsettingsd
    src: xsettingsd.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [xsettingsd, xsettings]

- name: Copy .Xresources
  become: no
  template:
    dest: /home/{{ ansible_user }}/.Xresources
    src: xresources.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: xresources

- name: Ensures /home/{{ ansible_user }}/.urxvt dir exists
  become: no
  file: path=/home/{{ ansible_user }}/.urxvt state=directory
  tags: urxvt

- name: Urxvt clipboard
  become: no
  template:
    dest: /home/{{ ansible_user }}/.urxvt/clipboard
    src: clipboard.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [clipboard, urxvt]

- name: Urxvt url select
  become: no
  template:
    dest: /home/{{ ansible_user }}/.urxvt/url_select
    src: url_select.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [url_select, urxvt]

- name: Urxvt keyboard select
  become: no
  template:
    dest: /home/{{ ansible_user }}/.urxvt/keyboard_select
    src: keyboard_select.j2
    backup: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: [keyboard_select, urxvt]

- name: Install himawaripy
  become: no
  pip:
    name: git+https://github.com/boramalper/himawaripy.git
  tags: [himawaripy, himawari, wallpaper]

- name: Periodically update images and set them as new background.
  become: no
  cron:
    user: "{{ ansible_user }}"
    name: "update background"
    minute: "*/15"
    job: "/usr/local/bin/himawaripy -l 4"
  tags: [bg, wallpaper, himararipy, himawari]